name: Simple CI/CD Pipeline

# Триггер запуска: push в ветку main
on:
  push:
    branches:
      - main

jobs:
  run-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Print CI/CD message
      run: echo "CI/CD!"
